import { Suspense } from 'react';
import { Inter } from 'next/font/google';

import { Providers } from './provider';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'My Dietary Record',
	description: 'Generated by create next app, using Geist UI & Vercel KV',
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<meta
				name="viewport"
				content="width=device-width, user-scalable=no, initial-scale=1, maximum-scale=1"
			></meta>
			<body className={inter.className}>
				<Suspense>
					<Providers>{children}</Providers>
				</Suspense>
			</body>
		</html>
	);
}
